// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  card: defineAsyncComponent(() => import("./Card/index.vue")),
  feature: defineAsyncComponent(() => import("./Feature/index.vue")),
  heading: defineAsyncComponent(() => import("./Heading/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  testimonial: defineAsyncComponent(() => import("./Testimonial/index.vue")),
});
