// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  feature: defineAsyncComponent(() => import("./Feature/index.vue")),
  heading: defineAsyncComponent(() => import("./Heading/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
